config/routes.rb
RstatUs::Application.routes.draw do
  root :to => "static#homepage", :constraints => lambda {|x| x.session[:user_id] == nil}
  root :to => "updates#timeline", :constraints => lambda {|x| x.session[:user_id] != nil}

  # Sessions
  resources :sessions, :only => [:new, :create, :destroy]
  match "/login", :to => "sessions#new"
  match "/logout", :to => "sessions#destroy", :via => :post

  # Static
  match "about",       :to => "static#about"
  match "contact",     :to => "static#contact"
  match "follow",      :to => "static#follow", :via => :get
  match "help",        :to => "static#help"
  match "open_source", :to => "static#open_source"

  # External Auth
  # If we add more valid auth providers, they will need to be added
  # to this route's constraints
  match '/auth/:provider/callback', :to => 'auth#auth', :constraints => {:provider => /twitter/}
  match '/auth/:provider/callback', :to => 'auth#invalid_auth_provider'
  match '/auth/failure', :to => 'auth#failure'
  match '/users/:username/auth/:provider', :via => :delete, :to => "auth#destroy", :constraints => {:username => /[^\/]+/ }

  # Users
  match 'users/:id.:format', :to => "users#show", :constraints => { :id => /[^\/]+/, :format => /json/ }
  resources :users, :constraints => { :id => /[^\/]+/ }
  match 'users/:id/confirm_delete', :to => "users#confirm_delete", :constraints => { :id => /[^\/]+/ }, :as => "account_deletion_confirmation", :via => :get
  match "users/:id/feed", :to => "users#feed", :as => "user_feed", :constraints => { :id => /[^\/]+/ }
  match 'users/:id/followers', :to => "users#followers", :constraints => { :id => /[^\/]+/ }, :as => "followers"
  match 'users/:id/following', :to => "users#following", :constraints => { :id => /[^\/]+/ }, :as => "following"

  # Users - manage avatar
  match '/users/:username/avatar', :via => :delete, :to => "avatar#destroy", :constraints => {:username => /[^\/]+/ }, :as => "avatar"

  # Users - confirm email
  match 'confirm_email/:token', :to => "users#confirm_email"

  # Users - forgot/reset password
  match 'forgot_password', :to => "users#forgot_password_new", :via => :get, :as => "forgot_password"
  match 'forgot_password', :to => "users#forgot_password_create", :via => :post
  match 'forgot_password_confirm', :to => "users#forgot_password_confirm", :via => :get, :as => "forgot_password_confirm"
  match 'reset_password', :to => "users#reset_password_new", :via => :get
  match 'reset_password', :to => "users#reset_password_create", :via => :post
  match 'reset_password/:token', :to => "users#reset_password_with_token", :via => :get, :as => "reset_password"

  # Updates
  resources :updates, :only => [:index, :show, :create, :destroy]
  match "/timeline", :to => "updates#timeline"
  match "/replies", :to => "updates#replies"
  match "/export", :to => "updates#export", :via => :get

  # Search
  resource :search, :only => :show

  # Autocomplete
  get "/autocomplete" => "users#autocomplete", :format => "json"

  # feeds
  resources :feeds, :only => :show

  # Webfinger
  match '.well-known/host-meta', :to => "webfinger#host_meta"
  match 'users/:username/xrd.xml', :to => "webfinger#xrd", :as => "user_xrd", :constraints => { :username => /[^\/]+/ }

  # Salmon
  match 'feeds/:id/salmon', :to => "salmon#feeds"

  # Subscriptions
  resources :subscriptions, :except => [:update]
  match 'subscriptions/:id.atom', :to => "subscriptions#post_update", :via => :post
  match 'subscriptions/:id.atom', :to => "subscriptions#show", :via => :get

  # Admin
  match '/admin', :to => "admin#update", :via => :put
  match '/admin', :to => "admin#index"
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_filter :find_user, :only => [:show, :edit, :update, :feed, :following, :followers]
  before_filter :require_user, :only => [:edit, :update, :confirm_delete, :destroy]

  def index
    @title = "users"
    set_params_page
    if params[:search].blank?
      @authors = Author.paginate(:page => params[:page], :per_page => params[:per_page])
    else
      begin
        @authors = Author.search(params)
      rescue RegexpError
        flash[:error] = "Please enter a valid search term"
        redirect_to users_path and return
      end

      unless @authors.empty?
        @authors = @authors.paginate(:page => params[:page], :per_page => params[:per_page])
        set_pagination_buttons(@authors, :search => params[:search])
      end
    end
  end

  def show
    if @user.nil?
      render :file => "#{Rails.root}/public/404", :status => 404
    elsif @user.username != params[:id] # case difference
      @title = @user.username
      redirect_to user_path(@user)
    else
      set_params_page
      @title = @user.username
      @author  = @user.author
      @updates = @user.updates
      @updates = @updates.paginate(:page => params[:page], :per_page => params[:per_page])

      set_pagination_buttons(@updates)

      headers['Link'] = "<#{user_xrd_path(@user.author)}>; rel=\"lrdd\"; type=\"application/xrd+xml\""

      respond_to do |format|
        format.html
        format.json {
          render :json => @updates.map{ |u| UpdateJsonDecorator.decorate(u) }
        }
      end

    end
  end

  def edit
    # While it might be cool to edit other people's profiles, we probably
    # shouldn't let you do that. We're no fun.
    if @user == current_user
      render :edit
    else
      redirect_to user_path(params[:id])
    end
  end

  def update
    if @user == current_user
      @user.update_profile!(params)

      unless @user.errors.any?
        unless @user.email.blank? || @user.email_confirmed
          Notifier.send_confirm_email_notification(@user.email, @user.create_token)
          flash[:notice] = "A link to confirm your updated email address has been sent to #{@user.email}."
        else
          flash[:notice] = "Profile saved!"
        end

        redirect_to user_path(@user)
      else
        error_message = render_to_string :partial => 'users/errors',
                                         :locals => {:user => @user}
        flash[:error] = error_message.html_safe

        render :edit
      end
    else
      redirect_to user_path(params[:id])
    end
  end

  def new
    params[:username] = session[:nickname]
    @user = User.new
  end

  def create
    params[:author] = Author.create_from_session!(session, params, root_url)

    @user = User.new :email    => params[:email],
                     :author   => params[:author],
                     :username => params[:username],
                     :password => params[:password]

    if @user.save
      Authorization.create_from_session!(session, @user)

      flash[:notice] = "Thanks! You're all signed up with #{@user.username} for your username."

      sign_in(@user)
      redirect_to root_path
    else
      render :new
    end
  end

  def autocomplete
    @json = current_user.autocomplete(params[:term])

    render :json => @json
  end

  # This is pretty much the same thing as /feeds/your_feed_id.atom, but we
  # wanted to have a really nice URL for it, and not just the ugly one.
  def feed
    if @user
      redirect_to feed_path(@user.feed, :format => :atom)
    else
      render :file => "#{Rails.root}/public/404", :status => 404
    end
  end

  # Who do you think is a really neat person? This page will show it to the
  # world, so pick wisely!
  def following
    if @user.nil?
      render :file => "#{Rails.root}/public/404", :status => 404
    # If the username's case entered in the URL is different than the case
    # specified by that user, redirect to the case that the user prefers
    elsif @user.username != params[:id]
      redirect_to following_path(@user.username)
    else
      set_params_page

      @feeds = @user.following

      @feeds = @feeds.paginate(:page => params[:page], :per_page => params[:per_page], :order => :id.desc)

      set_pagination_buttons(@feeds)

      @authors = @feeds.map{|f| f.author}

      if @user == current_user
        title = "You're following"
      else
        title = "@#{@user.username} is following"
      end

      respond_to do |format|
        format.html { render "users/list", :locals => {:title => title, :list_class => "friends"} }
        format.json { render :json => @authors }
      end
    end
  end

  # This shows off how cool you are: I hope you've got the biggest number of
  # followers. Only one way to find out...
  def followers
    if @user.nil?
      render :file => "#{Rails.root}/public/404", :status => 404
    # If the username's case entered in the URL is different than the case
    # specified by that user, redirect to the case that the user prefers
    elsif @user.username != params[:id]
      redirect_to followers_path(@user.username)
    else
      set_params_page

      @feeds = @user.followers

      @feeds = @feeds.paginate(:page => params[:page], :per_page => params[:per_page], :order => :id.desc)

      set_pagination_buttons(@feeds)

      @authors = @feeds.map{|f| f.author}

      #build title
      if @user == current_user
        title = "Your followers"
      else
        title = "@#{@user.username}'s followers"
      end

      render "users/list", :locals => {:title => title, :list_class => "followers"}
    end
  end

  # If we can't find a user in mongo or the token is expired give
  # them some information and redirect.
  #
  # Once an email has been confirmed there is no reason to leave
  # the token set so let's nil it out. The reset token method runs
  # save so we don't need to do that anymore
  def confirm_email
    user = User.first(:perishable_token => params[:token])
    if user.nil?
      flash[:error] = "Can't find User Account for this link."
      redirect_to root_path
    elsif user.token_expired?
      flash[:error] = "Your link is no longer valid, please request a new one."
      redirect_to root_path
    else
      user.email_confirmed = true
      user.reset_perishable_token
      # Register a session for the user
      sign_in(user)
      flash[:notice] = "Email successfully confirmed."
      redirect_to root_path
    end
  end

  # Passwords can be reset by unauthenticated users by navigating to the forgot
  # password and page and submitting the email address they provided.
  def forgot_password_new
    render "login/forgot_password"
  end

  # We've got a pretty solid forgotten password implementation. It's simple:
  # the email address is looked up, if no user is found an error is provided.
  # If a user is found a token is generated and an email is sent to the user
  # with the url to reset their password. Users are then redirected to the
  # confirmation page to prevent repost issues
  def forgot_password_create
    unless params[:email] =~ /^([\w\.%\+\-]+)@([\w\-]+\.)+([\w]{2,})$/i
      flash[:error] = "You didn't enter a correct email address. Please check your email and try again."
      return render "login/forgot_password"
    end

    user = User.first(:email => params[:email])

    if user.nil?
      flash[:error] = "Your account could not be found, please check your email and try again."
      render "login/forgot_password"
    else
      Notifier.send_forgot_password_notification(user.email, user.create_token)
      # Redirect to try to avoid repost issues
      session[:fp_email] = user.email
      redirect_to forgot_password_confirm_path
    end
  end

  # Forgot password confirmation screen, displays email address that the email
  # was sent to
  def forgot_password_confirm
    @email = session.delete(:fp_email)
    render "login/forgot_password_confirm"
  end

  def reset_password_new
    if not logged_in?
      redirect_to forgot_password_path
    else
      render "login/password_reset"
    end
  end

  # Submitted passwords are checked for length and confirmation. Once the
  # password has been reset the user is redirected to /
  def reset_password_create
    user = User.first(:perishable_token => params[:token]) if params[:token]
    user = nil if user && user.token_expired?

    redirect_to forgot_password_path unless user
    password_service = PasswordService.new(user, params)

    if password_service.invalid?
      flash[:error] = password_service.message
      url = reset_password_path(params[:token])
    else
      password_service.reset_password
      flash[:notice] = "Password successfully set"
      url = root_path
    end

    redirect_to url
  end

  # Public reset password page, accessible via a valid token. Tokens are only
  # valid for 2 days and are unique to that user. The user is found using the
  # token and the reset password page is rendered
  def reset_password_with_token
    user = User.first(:perishable_token => params[:token])
    if user.nil? || user.token_expired?
      flash[:error] = "Your link is no longer valid, please request a new one."
      redirect_to forgot_password_path
    else
      @token = params[:token]
      @user  = user
      render "login/password_reset"
    end
  end

  def confirm_delete
  end

  def destroy
    if current_user && params[:username_confirmation] == current_user.username
      current_user.destroy
      sign_out
      flash[:notice] = "Your account has been deleted. We're sorry to see you go."
      redirect_to root_path
    elsif current_user
      flash[:notice] = "Nothing was deleted since you did not type your username."
      redirect_to edit_user_path
    else
      redirect_to root_path
    end
  end

  private

  def find_user
    if @user = User.find_by_case_insensitive_username(params[:id])
      @user = UserDecorator.decorate(@user)
    end
  end
end

app/views/users/_errors.haml
- if user && user.errors.any?
  %div{:id => "error"}
    %div{:id => "error_explanation"}
      %strong= "Sorry, #{pluralize(user.errors.count, "error")} we need you to fix:"
      %ul
        - user.errors.full_messages.each do |msg|
          %li= msg

app/views/users/_follow_user.html.haml
= form_tag "/subscriptions" do
  %input{:type => "hidden", :name => "subscribe_to", :value => feed_id}
  %input.button.follow{:type => "submit", :value => "Follow", :id => "follow-#{feed_id}"}

app/views/users/_list.haml
#users
  %ul.user-list{:class => list_class}
    - authors.each_with_index do |author, i|
      - next if author.nil?
      %li.user{:class => i%2 == 0 ? "even" : "odd"}
        = AuthorDecorator.decorate(author).avatar

        .info
          %a{:href => author.url, :rel => 'user messages'}
            %b
              %span.user-name
                = author.display_name

            (<span class="user-text">#{author.username}</span>)
          .bio
            %span.description
              = author.bio

        - if current_user && current_user.feed != author.feed && author.feed
          - following = current_user.following_author?(author)
          .follow{:class => (following ? "negative" : "positive")}
            - if following
              = form_tag "/subscriptions/#{author.feed.id}" do
                %input{:type => "hidden", :name => "_method", :value => "delete"}
                = submit_tag "Unfollow", :class => "button unfollow", :id => "unfollow-#{author.feed.id}", :confirm => t(:unfollow, :scope => :confirms)
            - else
              = render :partial => "follow_user", :locals => { :feed_id => author.feed.id }

app/views/users/confirm_delete.haml
#delete
  %h3 Warning

  %p
    You are about to delete your account. This will also delete all your status updates, and this cannot be undone.

  %p
    If you are sure you want to do this, please type your username as confirmation:

  = form_tag user_path(current_user), :class => "delete_account_confirm" do
    %input{:type => "hidden", :name => "_method", :value => "delete"}
    %input{:type => :text, :name => :username_confirmation, :class => "username"}

    -# We have both a submit button and links here because of a Firefox
    -# CSS bug that sets line-height on buttons that can't be overridden.
    -# Since Cancel should be a link that goes back to the edit profile
    -# page, to match the height in Firefox, both Delete and Cancel are links.
    -# Having the submit button, which is hidden using CSS, allows enter to
    -# submit the form and makes something that will work without javascript.

    %input{:type => "submit", :value => "Delete Account", :class => "delete_account_submit button"}
    = link_to "Delete Account", "#", :id => "delete_account", :class => "button destructive_action"
    = link_to "Cancel", edit_user_path(current_user), :class => "button"

app/views/users/edit.haml
- @profile_sidebar = false

- content_for :sidebar do
  = render :partial => "shared/sidebar/gravatar", :locals => {:user => @user}

#profile
  %h3= "Edit Profile for @#{current_user.username}"

  = form_for current_user, :html => {:name => "profile_update_form", :id => "profile-update"} do |f|
    .form-section
      = render :partial => "shared/field", :locals => {:obj => @user.author, :attr => :username, :params => params}
      = render :partial => "shared/field", :locals => {:obj => @user.author, :attr => :name, :params => params}

    .form-section
      = render :partial => "shared/field", :locals => {:attr => :password, :as => :password}
      = render :partial => "shared/field", :locals => {:attr => :password_confirm, :lbl => "Confirm Password", :as => :password}

    .form-section
      = render :partial => "shared/field", :locals => {:obj => @user.author, :attr => :email, :params => params}
      = render :partial => "shared/field", :locals => {:obj => @user.author, :attr => :website, :params => params}
      = render :partial => "shared/field", :locals => {:obj => @user.author, :attr => :bio, :as => :text, :params => params}

    - if @user.twitter?
      .form-section.preferences
        .section-label
          Preferences
        .input
          = f.check_box("always_send_to_twitter")
          %label{:for => "user_always_send_to_twitter"}
            Always post updates to Twitter?

    .form-submit
      %input.button{:type => "submit", :value => "Save"}
- content_for :bottom do
  .avatar.bottom-block
    %h4 Avatar
    .avatar-management
      - if @user.author.image_url.present?
        = image_tag(@user.author.avatar_url, :class => "photo user-image", :alt => "avatar")
        %span.description
          Saved from a linked account
        = form_tag(avatar_path(@user.author), :method => "delete", :name => "avatar_delete_form", :id => "avatar-delete") do
          %input.button.destructive_action{:type => "submit", :value => "Remove Avatar"}
      - elsif @user.author.email.present?
        = image_tag(@user.author.avatar_url, :class => "photo user-image", :alt => "avatar")
        %span.description
          = "Gravatar using #{@user.author.email}"
        = link_to "Go to Gravatar to change", Author::GRAVATAR_SIGNUP, :class => "button"
      - else
        = image_tag(asset_path(RstatUs::DEFAULT_AVATAR), :class => "photo user-image", :alt => "avatar")
        %span.description
          = "Add an email to your profile above in order to use "
          = link_to("Gravatar", Author::GRAVATAR_SIGNUP)
          = " to set a custom avatar!"

  .linked-accounts.bottom-block
    %h4 Linked Accounts
    .linked
      - if @user.twitter?
        %img.linked-image{:src => asset_path("twitter_newbird_blue.png"), :alt => "Twitter Account"}
        .linked-name="@#{@user.twitter.nickname}"

        = form_tag "/users/#{@user.username}/auth/twitter", :method => "delete", :class => "profile-update", :name => "profile_update_form" do
          %input.button.destructive_action{:type => "submit", :value => "Remove"}

      - else
        %form.profile-update{:action => "/auth/twitter", :method => "GET", :name => "profile_update_form"}
          %input.button{:type => "submit", :value => "Add Twitter Account"}

  .delete-account.bottom-block
    %h4 Delete Account

    .to_delete
      = link_to "Delete Account", account_deletion_confirmation_path, :class => "button destructive_action"

app/views/users/index.haml
- title("Users")
- content_for :title do
  = "Users"

- content_for :top do
  #users-search.search
    %form.users-search{:method => :get, :action => "/users"}
      %input{:name => "search", :type => "text", :value => params[:search]}
      %input{:type => "submit", :value => "Search", :class => "button"}

- if @authors.empty?
  .empty
    Sorry, no users that match.
- else
  = render :partial => "users/list", :locals => {:authors => @authors, :list_class => "search"}

= render :partial => "shared/pagination"

app/views/users/list.haml
- title(title)
- content_for :title do
  = title

- if @authors.empty?
  %h3 No one yet!
  Well, that's kind of boring.  Why not check out the links on the left to browse users or search rstat.us updates?

- else
  = render :partial => "users/list", :locals => {:authors => @authors, :list_class => @list_class}

= render "shared/pagination"

app/views/users/new.haml
- content_for :title do
  Pick a username

- content_for :top do
  = render :partial => "users/errors", :locals => {:user => @user}

%p You're almost done! Choose a username to log in.

= form_tag "/users" do
  .form-section
    = render :partial => "shared/field", :locals => {:attr => :username, :params => params}

  .form-submit
    %input.button{:type => "submit", :value => "Finish Signup"}

app/views/users/show.haml
- @profile_sidebar = false
- title "@#{@author.username}'s Profile"

- content_for :sidebar do
  - if @author.user == current_user
    = render :partial => "shared/sidebar/gravatar", :locals => {:user => @author.user}

- content_for :top do
  #profile.vcard
    #users
      %ul.single
        %li.user

          %h3.fn
            %span.user-name= @author.display_name
          .nickname  @<span class="user-text">#{@author.username}</span>

          .follow-wrap
            - unless current_user and @author.user == current_user
              #follow
                - if current_user and current_user.following_author? @author
                  .negative
                    = form_tag "/subscriptions/#{@author.feed.id}" do
                      %input{:type => "hidden", :name => "_method", :value => "delete"}
                        %input.button.unfollow{:type => "submit", :value => "Unfollow", :id => "unfollow-#{@author.feed.id}"}
                - elsif current_user
                  = render :partial => "follow_user", :locals => { :feed_id => @author.feed.id }

            - if @author.user == current_user
              .edit
                %a{:href => edit_user_path(@author.username)} Edit
              .export
                %a= link_to "Export all updates", export_path

          - unless @author.website.blank? or @author.bio.blank?
            .info
              - unless @author.website.blank?
                .website
                  = @author.website_link

              %p.note
                %span.description= @author.bio

          %ul.stats
            %li.update-count
              %a{ :href => "#profile_updates", :rel => 'messages-me' }
                %span.icon
                %span.number= @author.feed.updates.count
                Updates
            %li.following-count
              %a{ :href => "/users/#{@author.username}/following", :rel => 'users-friends' }
                %span.icon
                %span.number= @author.user.following.length
                Following
            %li.follower-count
              %a{ :href => "/users/#{@author.username}/followers", :rel => 'users-followers'}
                %span.icon
                %span.number= @author.user.followers.length
                Followers
            %li.rss
              %a{ :href => user_feed_path(@author.username)}
                %span.icon
                Atom feed


= render :partial => "updates/list", :locals => {:updates => @updates, :id => "profile_updates", :no_highlight => true, :list_class => "messages-user"}